#端口号
server:
  port: 25000
#  ssl:
#    key-store: classpath:glimmer.org.cn.jks
#    key-store-password: j95zw5d263cp0
#    key-store-type: JKS

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: newuser
    password: newpassword
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 6000MB
  data:
    redis:
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100
  mail:
    username: 1727448271@qq.com
    password: xfjbtleqkdfoeegg
    host: smtp.qq.com
    properties:
      mail:
        debug: false
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    default-encoding: utf-8
    port: 465

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
    map-underscore-to-camel-case: true

