#端口号
server:
  port: 25000
#  port: 24999
  ssl:
    key-store: classpath:backend.glimmer.org.cn.pfx
    key-store-password: gp5h63b4z2xnr
    key-store-type: PKCS12 # pfx 类型的证书对应是 PKCS12
    enabled: true
    client-auth: none

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: newuser
    password: newpassword
#    username: root
#    password: 102030aoboco
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 6000MB
  data:
    redis:
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100
  mail:
    username: glimmer@mcyou.cc
    password: Glimmernb!
    host: smtp.mxhichina.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    default-encoding: utf-8
    port: 465

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
    map-underscore-to-camel-case: true

